# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instance.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='instance.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0einstance.proto\x12\x05proto\"?\n\x0fInstanceRequest\x12\x10\n\x08template\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\">\n\x10InstanceResponse\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x15\n\rinstance_name\x18\x02 \x01(\t2V\n\x0fInstanceService\x12\x43\n\x0e\x43reateInstance\x12\x16.proto.InstanceRequest\x1a\x17.proto.InstanceResponse\"\x00\x62\x06proto3'
)




_INSTANCEREQUEST = _descriptor.Descriptor(
  name='InstanceRequest',
  full_name='proto.InstanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='template', full_name='proto.InstanceRequest.template', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='proto.InstanceRequest.model', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='proto.InstanceRequest.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=88,
)


_INSTANCERESPONSE = _descriptor.Descriptor(
  name='InstanceResponse',
  full_name='proto.InstanceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='proto.InstanceResponse.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instance_name', full_name='proto.InstanceResponse.instance_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['InstanceRequest'] = _INSTANCEREQUEST
DESCRIPTOR.message_types_by_name['InstanceResponse'] = _INSTANCERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstanceRequest = _reflection.GeneratedProtocolMessageType('InstanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSTANCEREQUEST,
  '__module__' : 'instance_pb2'
  # @@protoc_insertion_point(class_scope:proto.InstanceRequest)
  })
_sym_db.RegisterMessage(InstanceRequest)

InstanceResponse = _reflection.GeneratedProtocolMessageType('InstanceResponse', (_message.Message,), {
  'DESCRIPTOR' : _INSTANCERESPONSE,
  '__module__' : 'instance_pb2'
  # @@protoc_insertion_point(class_scope:proto.InstanceResponse)
  })
_sym_db.RegisterMessage(InstanceResponse)



_INSTANCESERVICE = _descriptor.ServiceDescriptor(
  name='InstanceService',
  full_name='proto.InstanceService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=154,
  serialized_end=240,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateInstance',
    full_name='proto.InstanceService.CreateInstance',
    index=0,
    containing_service=None,
    input_type=_INSTANCEREQUEST,
    output_type=_INSTANCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INSTANCESERVICE)

DESCRIPTOR.services_by_name['InstanceService'] = _INSTANCESERVICE

# @@protoc_insertion_point(module_scope)
