# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instance.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='instance.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0einstance.proto\x12\x05proto\"\x86\x01\n\x0bImageConfig\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x12\n\ndata_label\x18\x04 \x01(\t\x12\x14\n\x0ctarget_label\x18\x05 \x01(\t\x12\x10\n\x08template\x18\x06 \x01(\t\x12\r\n\x05title\x18\x07 \x01(\t\"\x86\x01\n\x12\x43reateImageRequest\x12\x12\n\nrepository\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t\x12\x11\n\tdata_file\x18\x03 \x01(\x0c\x12\x12\n\nmodel_file\x18\x04 \x01(\x0c\x12(\n\x0cimage_config\x18\x05 \x01(\x0b\x32\x12.proto.ImageConfig\";\n\x13\x43reateImageResponse\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12\x12\n\nimage_size\x18\x02 \x01(\x03\"5\n\x12\x44\x65leteImageRequest\x12\x12\n\nrepository\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t\"&\n\x13\x44\x65leteImageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"8\n\x15\x43reateInstanceRequest\x12\x12\n\nimage_name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"D\n\x16\x43reateInstanceResponse\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x15\n\rinstance_name\x18\x02 \x01(\t\"*\n\x13InstanceInfoRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\"&\n\x14InstanceInfoResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"@\n\x16OperateInstanceRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\"*\n\x17OperateInstanceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x94\x03\n\x0fInstanceService\x12\x46\n\x0b\x43reateImage\x12\x19.proto.CreateImageRequest\x1a\x1a.proto.CreateImageResponse\"\x00\x12\x46\n\x0b\x44\x65leteImage\x12\x19.proto.DeleteImageRequest\x1a\x1a.proto.DeleteImageResponse\"\x00\x12O\n\x0e\x43reateInstance\x12\x1c.proto.CreateInstanceRequest\x1a\x1d.proto.CreateInstanceResponse\"\x00\x12L\n\x0fGetInstanceInfo\x12\x1a.proto.InstanceInfoRequest\x1a\x1b.proto.InstanceInfoResponse\"\x00\x12R\n\x0fOperateInstance\x12\x1d.proto.OperateInstanceRequest\x1a\x1e.proto.OperateInstanceResponse\"\x00\x62\x06proto3'
)




_IMAGECONFIG = _descriptor.Descriptor(
  name='ImageConfig',
  full_name='proto.ImageConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='proto.ImageConfig.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='proto.ImageConfig.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='proto.ImageConfig.model', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_label', full_name='proto.ImageConfig.data_label', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_label', full_name='proto.ImageConfig.target_label', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='template', full_name='proto.ImageConfig.template', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='proto.ImageConfig.title', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=160,
)


_CREATEIMAGEREQUEST = _descriptor.Descriptor(
  name='CreateImageRequest',
  full_name='proto.CreateImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='repository', full_name='proto.CreateImageRequest.repository', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tag', full_name='proto.CreateImageRequest.tag', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_file', full_name='proto.CreateImageRequest.data_file', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_file', full_name='proto.CreateImageRequest.model_file', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_config', full_name='proto.CreateImageRequest.image_config', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=297,
)


_CREATEIMAGERESPONSE = _descriptor.Descriptor(
  name='CreateImageResponse',
  full_name='proto.CreateImageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_id', full_name='proto.CreateImageResponse.image_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_size', full_name='proto.CreateImageResponse.image_size', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=358,
)


_DELETEIMAGEREQUEST = _descriptor.Descriptor(
  name='DeleteImageRequest',
  full_name='proto.DeleteImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='repository', full_name='proto.DeleteImageRequest.repository', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tag', full_name='proto.DeleteImageRequest.tag', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=413,
)


_DELETEIMAGERESPONSE = _descriptor.Descriptor(
  name='DeleteImageResponse',
  full_name='proto.DeleteImageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='proto.DeleteImageResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=453,
)


_CREATEINSTANCEREQUEST = _descriptor.Descriptor(
  name='CreateInstanceRequest',
  full_name='proto.CreateInstanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_name', full_name='proto.CreateInstanceRequest.image_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='proto.CreateInstanceRequest.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=511,
)


_CREATEINSTANCERESPONSE = _descriptor.Descriptor(
  name='CreateInstanceResponse',
  full_name='proto.CreateInstanceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='proto.CreateInstanceResponse.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instance_name', full_name='proto.CreateInstanceResponse.instance_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=513,
  serialized_end=581,
)


_INSTANCEINFOREQUEST = _descriptor.Descriptor(
  name='InstanceInfoRequest',
  full_name='proto.InstanceInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='proto.InstanceInfoRequest.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=583,
  serialized_end=625,
)


_INSTANCEINFORESPONSE = _descriptor.Descriptor(
  name='InstanceInfoResponse',
  full_name='proto.InstanceInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='proto.InstanceInfoResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=627,
  serialized_end=665,
)


_OPERATEINSTANCEREQUEST = _descriptor.Descriptor(
  name='OperateInstanceRequest',
  full_name='proto.OperateInstanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='proto.OperateInstanceRequest.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation', full_name='proto.OperateInstanceRequest.operation', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=667,
  serialized_end=731,
)


_OPERATEINSTANCERESPONSE = _descriptor.Descriptor(
  name='OperateInstanceResponse',
  full_name='proto.OperateInstanceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='proto.OperateInstanceResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=733,
  serialized_end=775,
)

_CREATEIMAGEREQUEST.fields_by_name['image_config'].message_type = _IMAGECONFIG
DESCRIPTOR.message_types_by_name['ImageConfig'] = _IMAGECONFIG
DESCRIPTOR.message_types_by_name['CreateImageRequest'] = _CREATEIMAGEREQUEST
DESCRIPTOR.message_types_by_name['CreateImageResponse'] = _CREATEIMAGERESPONSE
DESCRIPTOR.message_types_by_name['DeleteImageRequest'] = _DELETEIMAGEREQUEST
DESCRIPTOR.message_types_by_name['DeleteImageResponse'] = _DELETEIMAGERESPONSE
DESCRIPTOR.message_types_by_name['CreateInstanceRequest'] = _CREATEINSTANCEREQUEST
DESCRIPTOR.message_types_by_name['CreateInstanceResponse'] = _CREATEINSTANCERESPONSE
DESCRIPTOR.message_types_by_name['InstanceInfoRequest'] = _INSTANCEINFOREQUEST
DESCRIPTOR.message_types_by_name['InstanceInfoResponse'] = _INSTANCEINFORESPONSE
DESCRIPTOR.message_types_by_name['OperateInstanceRequest'] = _OPERATEINSTANCEREQUEST
DESCRIPTOR.message_types_by_name['OperateInstanceResponse'] = _OPERATEINSTANCERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageConfig = _reflection.GeneratedProtocolMessageType('ImageConfig', (_message.Message,), {
  'DESCRIPTOR' : _IMAGECONFIG,
  '__module__' : 'instance_pb2'
  # @@protoc_insertion_point(class_scope:proto.ImageConfig)
  })
_sym_db.RegisterMessage(ImageConfig)

CreateImageRequest = _reflection.GeneratedProtocolMessageType('CreateImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEIMAGEREQUEST,
  '__module__' : 'instance_pb2'
  # @@protoc_insertion_point(class_scope:proto.CreateImageRequest)
  })
_sym_db.RegisterMessage(CreateImageRequest)

CreateImageResponse = _reflection.GeneratedProtocolMessageType('CreateImageResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEIMAGERESPONSE,
  '__module__' : 'instance_pb2'
  # @@protoc_insertion_point(class_scope:proto.CreateImageResponse)
  })
_sym_db.RegisterMessage(CreateImageResponse)

DeleteImageRequest = _reflection.GeneratedProtocolMessageType('DeleteImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEIMAGEREQUEST,
  '__module__' : 'instance_pb2'
  # @@protoc_insertion_point(class_scope:proto.DeleteImageRequest)
  })
_sym_db.RegisterMessage(DeleteImageRequest)

DeleteImageResponse = _reflection.GeneratedProtocolMessageType('DeleteImageResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEIMAGERESPONSE,
  '__module__' : 'instance_pb2'
  # @@protoc_insertion_point(class_scope:proto.DeleteImageResponse)
  })
_sym_db.RegisterMessage(DeleteImageResponse)

CreateInstanceRequest = _reflection.GeneratedProtocolMessageType('CreateInstanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEINSTANCEREQUEST,
  '__module__' : 'instance_pb2'
  # @@protoc_insertion_point(class_scope:proto.CreateInstanceRequest)
  })
_sym_db.RegisterMessage(CreateInstanceRequest)

CreateInstanceResponse = _reflection.GeneratedProtocolMessageType('CreateInstanceResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEINSTANCERESPONSE,
  '__module__' : 'instance_pb2'
  # @@protoc_insertion_point(class_scope:proto.CreateInstanceResponse)
  })
_sym_db.RegisterMessage(CreateInstanceResponse)

InstanceInfoRequest = _reflection.GeneratedProtocolMessageType('InstanceInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSTANCEINFOREQUEST,
  '__module__' : 'instance_pb2'
  # @@protoc_insertion_point(class_scope:proto.InstanceInfoRequest)
  })
_sym_db.RegisterMessage(InstanceInfoRequest)

InstanceInfoResponse = _reflection.GeneratedProtocolMessageType('InstanceInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _INSTANCEINFORESPONSE,
  '__module__' : 'instance_pb2'
  # @@protoc_insertion_point(class_scope:proto.InstanceInfoResponse)
  })
_sym_db.RegisterMessage(InstanceInfoResponse)

OperateInstanceRequest = _reflection.GeneratedProtocolMessageType('OperateInstanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPERATEINSTANCEREQUEST,
  '__module__' : 'instance_pb2'
  # @@protoc_insertion_point(class_scope:proto.OperateInstanceRequest)
  })
_sym_db.RegisterMessage(OperateInstanceRequest)

OperateInstanceResponse = _reflection.GeneratedProtocolMessageType('OperateInstanceResponse', (_message.Message,), {
  'DESCRIPTOR' : _OPERATEINSTANCERESPONSE,
  '__module__' : 'instance_pb2'
  # @@protoc_insertion_point(class_scope:proto.OperateInstanceResponse)
  })
_sym_db.RegisterMessage(OperateInstanceResponse)



_INSTANCESERVICE = _descriptor.ServiceDescriptor(
  name='InstanceService',
  full_name='proto.InstanceService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=778,
  serialized_end=1182,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateImage',
    full_name='proto.InstanceService.CreateImage',
    index=0,
    containing_service=None,
    input_type=_CREATEIMAGEREQUEST,
    output_type=_CREATEIMAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteImage',
    full_name='proto.InstanceService.DeleteImage',
    index=1,
    containing_service=None,
    input_type=_DELETEIMAGEREQUEST,
    output_type=_DELETEIMAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateInstance',
    full_name='proto.InstanceService.CreateInstance',
    index=2,
    containing_service=None,
    input_type=_CREATEINSTANCEREQUEST,
    output_type=_CREATEINSTANCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetInstanceInfo',
    full_name='proto.InstanceService.GetInstanceInfo',
    index=3,
    containing_service=None,
    input_type=_INSTANCEINFOREQUEST,
    output_type=_INSTANCEINFORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='OperateInstance',
    full_name='proto.InstanceService.OperateInstance',
    index=4,
    containing_service=None,
    input_type=_OPERATEINSTANCEREQUEST,
    output_type=_OPERATEINSTANCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INSTANCESERVICE)

DESCRIPTOR.services_by_name['InstanceService'] = _INSTANCESERVICE

# @@protoc_insertion_point(module_scope)
