# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iris.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='iris.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\niris.proto\x12\x05proto\"c\n\x0bTaskRequest\x12\x14\n\x0csepal_length\x18\x01 \x01(\t\x12\x13\n\x0bsepal_width\x18\x02 \x01(\t\x12\x14\n\x0cpetal_length\x18\x03 \x01(\t\x12\x13\n\x0bpetal_width\x18\x04 \x01(\t\"h\n\x0cTaskResponse\x12*\n\x06result\x18\x01 \x03(\x0b\x32\x1a.proto.TaskResponse.Result\x1a,\n\x06Result\x12\r\n\x05\x63lass\x18\x01 \x01(\t\x12\x13\n\x0bprobability\x18\x02 \x01(\t2I\n\x0ePredictionTask\x12\x37\n\nLaunchTask\x12\x12.proto.TaskRequest\x1a\x13.proto.TaskResponse\"\x00\x62\x06proto3'
)




_TASKREQUEST = _descriptor.Descriptor(
  name='TaskRequest',
  full_name='proto.TaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sepal_length', full_name='proto.TaskRequest.sepal_length', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sepal_width', full_name='proto.TaskRequest.sepal_width', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='petal_length', full_name='proto.TaskRequest.petal_length', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='petal_width', full_name='proto.TaskRequest.petal_width', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=120,
)


_TASKRESPONSE_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='proto.TaskResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='class', full_name='proto.TaskResponse.Result.class', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='probability', full_name='proto.TaskResponse.Result.probability', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=226,
)

_TASKRESPONSE = _descriptor.Descriptor(
  name='TaskResponse',
  full_name='proto.TaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='proto.TaskResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TASKRESPONSE_RESULT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=226,
)

_TASKRESPONSE_RESULT.containing_type = _TASKRESPONSE
_TASKRESPONSE.fields_by_name['result'].message_type = _TASKRESPONSE_RESULT
DESCRIPTOR.message_types_by_name['TaskRequest'] = _TASKREQUEST
DESCRIPTOR.message_types_by_name['TaskResponse'] = _TASKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskRequest = _reflection.GeneratedProtocolMessageType('TaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _TASKREQUEST,
  '__module__' : 'iris_pb2'
  # @@protoc_insertion_point(class_scope:proto.TaskRequest)
  })
_sym_db.RegisterMessage(TaskRequest)

TaskResponse = _reflection.GeneratedProtocolMessageType('TaskResponse', (_message.Message,), {

  'Result' : _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
    'DESCRIPTOR' : _TASKRESPONSE_RESULT,
    '__module__' : 'iris_pb2'
    # @@protoc_insertion_point(class_scope:proto.TaskResponse.Result)
    })
  ,
  'DESCRIPTOR' : _TASKRESPONSE,
  '__module__' : 'iris_pb2'
  # @@protoc_insertion_point(class_scope:proto.TaskResponse)
  })
_sym_db.RegisterMessage(TaskResponse)
_sym_db.RegisterMessage(TaskResponse.Result)



_PREDICTIONTASK = _descriptor.ServiceDescriptor(
  name='PredictionTask',
  full_name='proto.PredictionTask',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=228,
  serialized_end=301,
  methods=[
  _descriptor.MethodDescriptor(
    name='LaunchTask',
    full_name='proto.PredictionTask.LaunchTask',
    index=0,
    containing_service=None,
    input_type=_TASKREQUEST,
    output_type=_TASKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PREDICTIONTASK)

DESCRIPTOR.services_by_name['PredictionTask'] = _PREDICTIONTASK

# @@protoc_insertion_point(module_scope)
