# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import iris_pb2 as iris__pb2


class PredictionTaskStub(object):
    """python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. ./iris.proto

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LaunchTask = channel.unary_unary(
                '/proto.PredictionTask/LaunchTask',
                request_serializer=iris__pb2.TaskRequest.SerializeToString,
                response_deserializer=iris__pb2.TaskResponse.FromString,
                )


class PredictionTaskServicer(object):
    """python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. ./iris.proto

    """

    def LaunchTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictionTaskServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LaunchTask': grpc.unary_unary_rpc_method_handler(
                    servicer.LaunchTask,
                    request_deserializer=iris__pb2.TaskRequest.FromString,
                    response_serializer=iris__pb2.TaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.PredictionTask', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PredictionTask(object):
    """python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. ./iris.proto

    """

    @staticmethod
    def LaunchTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.PredictionTask/LaunchTask',
            iris__pb2.TaskRequest.SerializeToString,
            iris__pb2.TaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
